direct_mapped_cache: direct_mapped_cache
direct_mapped_cache: direct_mapped_cache.o
	g++ direct_mapped_cache.o -o direct_mapped_cache
direct_mapped_cache.o: direct_mapped_cache.cpp
clean:
	rm -rf *o direct_mapped_cache
